-- PublicEcho Large Seed File 2: 225 Bengaluru BBMP Wards
USE railway;

INSERT INTO `Wards` (`ward_id`, `ward_name`, `zone_name`, `city`) VALUES
(37, 'Peenya', 'RR Nagar', 'Bengaluru'),
(35, 'Yeshwanthpura', 'RR Nagar', 'Bengaluru'),
(36, 'Jalahalli', 'RR Nagar', 'Bengaluru'),
(34, 'JP Park', 'RR Nagar', 'Bengaluru'),
(41, 'Kottegepalya', 'RR Nagar', 'Bengaluru'),
(42, 'Srigandhadakaval', 'RR Nagar', 'Bengaluru'),
(43, 'Malathalli', 'RR Nagar', 'Bengaluru'),
(44, 'Jnana Bharathi ward', 'RR Nagar', 'Bengaluru'),
(45, 'Rajarajeshwari Nagar', 'RR Nagar', 'Bengaluru'),
(38, 'Laxmidevi Nagar', 'RR Nagar', 'Bengaluru'),
(40, 'Chowdeshwari Nagar', 'RR Nagar', 'Bengaluru'),
(39, 'Laggere', 'RR Nagar', 'Bengaluru'),
(203, 'Subrahmanyapura', 'South Zone', 'Bengaluru'),
(204, 'Vasanthpura', 'South Zone', 'Bengaluru'),
(206, 'Konanakunte', 'South Zone', 'Bengaluru'),
(207, 'RBI layout', 'South Zone', 'Bengaluru'),
(208, 'Anjanapura', 'South Zone', 'Bengaluru'),
(209, 'Gottigere', 'South Zone', 'Bengaluru'),
(212, 'Naganathapura', 'South Zone', 'Bengaluru'),
(202, 'Uttarahalli', 'South Zone', 'Bengaluru'),
(211, 'Begur', 'South Zone', 'Bengaluru'),
(210, 'Kalena Agrahara', 'South Zone', 'Bengaluru'),
(205, 'Yelchenahalli', 'South Zone', 'Bengaluru'),
(225, 'Kudlu', 'South Zone', 'Bengaluru'),
(86, 'Challakere', 'Mahadevapura', 'Bengaluru'),
(89, 'Vijinapura', 'Mahadevapura', 'Bengaluru'),
(93, 'Devasandra', 'Mahadevapura', 'Bengaluru'),
(87, 'Horamavu', 'Mahadevapura', 'Bengaluru'),
(94, 'A. Narayanapura', 'Mahadevapura', 'Bengaluru'),
(96, 'HAL Airport', 'Mahadevapura', 'Bengaluru'),
(90, 'Ramamurthy Nagar', 'Mahadevapura', 'Bengaluru'),
(88, 'Kalkere', 'Mahadevapura', 'Bengaluru'),
(91, 'K R Puram', 'Mahadevapura', 'Bengaluru'),
(92, 'Basavanapura', 'Mahadevapura', 'Bengaluru'),
(95, 'Vijnana Nagar', 'Mahadevapura', 'Bengaluru'),
(7, 'Thanisandra', 'Byatarayanapura', 'Bengaluru'),
(11, 'Kodigehalli', 'Byatarayanapura', 'Bengaluru'),
(9, 'Hebbal Kempapura', 'Byatarayanapura', 'Bengaluru'),
(5, 'Kogilu', 'Byatarayanapura', 'Bengaluru'),
(10, 'Byatarayanapura', 'Byatarayanapura', 'Bengaluru'),
(14, 'Kuvempu Nagar', 'Byatarayanapura', 'Bengaluru'),
(13, 'Vidyaranyapura', 'Byatarayanapura', 'Bengaluru'),
(12, 'Dodda Bommasandra', 'Byatarayanapura', 'Bengaluru'),
(8, 'Amrutahalli', 'Byatarayanapura', 'Bengaluru'),
(6, 'Jakkuru', 'Byatarayanapura', 'Bengaluru'),
(26, 'Dodda Bidarakallu', 'RR Nagar', 'Bengaluru'),
(30, 'Nagadevanahalli', 'RR Nagar', 'Bengaluru'),
(27, 'Lingadheeranahalli', 'RR Nagar', 'Bengaluru'),
(28, 'Herohalli', 'RR Nagar', 'Bengaluru'),
(29, 'Ullalu', 'RR Nagar', 'Bengaluru'),
(31, 'Bande Mutt', 'RR Nagar', 'Bengaluru'),
(32, 'Kengeri', 'RR Nagar', 'Bengaluru'),
(33, 'Hemmigepura', 'RR Nagar', 'Bengaluru'),
(17, 'Chikkasandra', 'Dasarahalli', 'Bengaluru'),
(15, 'Kammagondanahalli', 'Dasarahalli', 'Bengaluru'),
(16, 'Mallasandra', 'Dasarahalli', 'Bengaluru'),
(18, 'Bagalakunte', 'Dasarahalli', 'Bengaluru'),
(19, 'T Dasarahalli', 'Dasarahalli', 'Bengaluru'),
(20, 'Nalagadarenahalli', 'Dasarahalli', 'Bengaluru'),
(21, 'Chokkasandra', 'Dasarahalli', 'Bengaluru'),
(22, 'Peenya Industrial Area', 'Dasarahalli', 'Bengaluru'),
(23, 'Rajagopal Nagar', 'Dasarahalli', 'Bengaluru'),
(24, 'Hegganahalli', 'Dasarahalli', 'Bengaluru'),
(25, 'Sunkadakatte', 'Dasarahalli', 'Bengaluru'),
(52, 'Shakthi Ganapathi Nagar', 'West Zone', 'Bengaluru'),
(53, 'Vrisabhavathi Nagar', 'West Zone', 'Bengaluru'),
(51, 'Shankar Matt', 'West Zone', 'Bengaluru'),
(46, 'Rajiv Nagar', 'West Zone', 'Bengaluru'),
(47, 'Dr. Puneet Rajkumar', 'West Zone', 'Bengaluru'),
(49, 'Nagapura', 'West Zone', 'Bengaluru'),
(48, 'Mahalakshmipuram', 'West Zone', 'Bengaluru'),
(50, 'Nalvadi Krishna Raja Wadiyar', 'West Zone', 'Bengaluru'),
(54, 'Mattikere', 'West Zone', 'Bengaluru'),
(55, 'Malleswaram', 'West Zone', 'Bengaluru'),
(56, 'Aramane Nagara', 'West Zone', 'Bengaluru'),
(57, 'Rajamahal Guttahalli', 'West Zone', 'Bengaluru'),
(60, 'Gayithri Nagar', 'West Zone', 'Bengaluru'),
(59, 'Subramanya Nagar', 'West Zone', 'Bengaluru'),
(58, 'Kadu Malleshwar Ward', 'West Zone', 'Bengaluru'),
(67, 'Ganga Nagar', 'East Zone', 'Bengaluru'),
(63, 'Hebbala', 'East Zone', 'Bengaluru'),
(61, 'Radhakrishna Temple Ward', 'East Zone', 'Bengaluru'),
(66, 'Chamundi Nagara', 'East Zone', 'Bengaluru'),
(68, 'Jayachamarajendra  Nagar', 'East Zone', 'Bengaluru'),
(62, 'Sanjaya Nagar', 'East Zone', 'Bengaluru'),
(65, 'Manorayanapalya', 'East Zone', 'Bengaluru'),
(64, 'Vishwanath Nagenahalli', 'East Zone', 'Bengaluru'),
(70, 'Kushal Nagar', 'East Zone', 'Bengaluru'),
(71, 'Muneshwara Nagar', 'East Zone', 'Bengaluru'),
(69, 'Kaval Bairasandra', 'East Zone', 'Bengaluru'),
(74, 'Sagayarapuram', 'East Zone', 'Bengaluru'),
(75, 'Pulikeshinagar', 'East Zone', 'Bengaluru'),
(72, 'Devara Jeevanahalli', 'East Zone', 'Bengaluru'),
(73, 'S K Garden', 'East Zone', 'Bengaluru'),
(80, 'Kacharkanahalli', 'East Zone', 'Bengaluru'),
(81, 'Kammanahalli', 'East Zone', 'Bengaluru'),
(82, 'Banasavadi', 'East Zone', 'Bengaluru'),
(76, 'Hennur', 'East Zone', 'Bengaluru'),
(78, 'HBR Layout', 'East Zone', 'Bengaluru'),
(77, 'Nagavara', 'East Zone', 'Bengaluru'),
(79, 'Kadugondanahalli', 'East Zone', 'Bengaluru'),
(83, 'Subbayyanapalya', 'East Zone', 'Bengaluru'),
(84, 'Lingarajapura', 'East Zone', 'Bengaluru'),
(85, 'Maruthi Seva Nagar', 'East Zone', 'Bengaluru'),
(108, 'Cox Town', 'East Zone', 'Bengaluru'),
(113, 'Hoysala Nagar', 'East Zone', 'Bengaluru'),
(114, 'Jeevanbhima Nagar', 'East Zone', 'Bengaluru'),
(115, 'Konena Agrahara', 'East Zone', 'Bengaluru'),
(109, 'Benniganahalli', 'East Zone', 'Bengaluru'),
(110, 'C V Raman Nagar', 'East Zone', 'Bengaluru'),
(111, 'Kaggadasanapura', 'East Zone', 'Bengaluru'),
(112, 'New Tippasandara', 'East Zone', 'Bengaluru'),
(116, 'Ramaswamypalya', 'East Zone', 'Bengaluru'),
(117, 'Vasanthnagar', 'East Zone', 'Bengaluru'),
(120, 'Bharathi Nagar', 'East Zone', 'Bengaluru'),
(121, 'Ulsoor', 'East Zone', 'Bengaluru'),
(118, 'Sampangiram Nagar', 'East Zone', 'Bengaluru'),
(119, 'Shivaji Nagar', 'East Zone', 'Bengaluru'),
(167, 'Ashok Nagar', 'East Zone', 'Bengaluru'),
(166, 'Shanthi Nagar', 'East Zone', 'Bengaluru'),
(168, 'Nilasandra', 'East Zone', 'Bengaluru'),
(169, 'Vannarpet', 'East Zone', 'Bengaluru'),
(170, 'Jogupalya', 'East Zone', 'Bengaluru'),
(171, 'Domlur', 'East Zone', 'Bengaluru'),
(172, 'Agaram', 'East Zone', 'Bengaluru'),
(125, 'Okalipuram', 'West Zone', 'Bengaluru'),
(128, 'Chickpete', 'West Zone', 'Bengaluru'),
(122, 'Dattatreya Temple', 'West Zone', 'Bengaluru'),
(123, 'Gandhinagar', 'West Zone', 'Bengaluru'),
(124, 'Subhash Nagar', 'West Zone', 'Bengaluru'),
(126, 'Binnipete', 'West Zone', 'Bengaluru'),
(127, 'Cottonpete', 'West Zone', 'Bengaluru'),
(129, 'Dayananda Nagar', 'West Zone', 'Bengaluru'),
(134, 'Kamakshipalya', 'West Zone', 'Bengaluru'),
(131, 'Shivanagara', 'West Zone', 'Bengaluru'),
(132, 'Rajaji Nagar', 'West Zone', 'Bengaluru'),
(130, 'Sriramamandir', 'West Zone', 'Bengaluru'),
(133, 'Basaveshwara Nagar', 'West Zone', 'Bengaluru'),
(154, 'Rayapuram', 'West Zone', 'Bengaluru'),
(155, 'Devaraj Urs Nagar', 'West Zone', 'Bengaluru'),
(156, 'Chalavadipalya', 'West Zone', 'Bengaluru'),
(157, 'K R Market', 'West Zone', 'Bengaluru'),
(158, 'Chamrajapet', 'West Zone', 'Bengaluru'),
(159, 'Azad Nagar', 'West Zone', 'Bengaluru'),
(153, 'Padarayanapura', 'West Zone', 'Bengaluru'),
(101, 'Dodda Nekkundi', 'Mahadevapura', 'Bengaluru'),
(100, 'Garudachar Palya', 'Mahadevapura', 'Bengaluru'),
(99, 'Byrathi', 'Mahadevapura', 'Bengaluru'),
(97, 'Kadugodi', 'Mahadevapura', 'Bengaluru'),
(98, 'Hudi', 'Mahadevapura', 'Bengaluru'),
(103, 'White Field', 'Mahadevapura', 'Bengaluru'),
(102, 'AECS Layout', 'Mahadevapura', 'Bengaluru'),
(107, 'Bellanduru', 'Mahadevapura', 'Bengaluru'),
(104, 'Varthuru', 'Mahadevapura', 'Bengaluru'),
(106, 'Marathahalli', 'Mahadevapura', 'Bengaluru'),
(105, 'Munekollal', 'Mahadevapura', 'Bengaluru'),
(139, 'Mudalapalya', 'West Zone', 'Bengaluru'),
(141, 'Nagarabhavi', 'West Zone', 'Bengaluru'),
(136, 'Govindaraja Nagar', 'West Zone', 'Bengaluru'),
(135, 'Dr. Raj Kumar Agrahara Dasarahalli', 'West Zone', 'Bengaluru'),
(137, 'Marenahalli', 'West Zone', 'Bengaluru'),
(140, 'Maruthi Mandir ward', 'West Zone', 'Bengaluru'),
(142, 'Chandralayout', 'West Zone', 'Bengaluru'),
(143, 'Nayandahalli', 'West Zone', 'Bengaluru'),
(138, 'Kaveripura', 'West Zone', 'Bengaluru'),
(144, 'Kempapura Agrahara', 'West Zone', 'Bengaluru'),
(148, 'New Guddadahalli', 'West Zone', 'Bengaluru'),
(149, 'Gali Anjaneya Temple Ward', 'West Zone', 'Bengaluru'),
(150, 'Attiguppe', 'West Zone', 'Bengaluru'),
(151, 'Deepanjali Nagar', 'West Zone', 'Bengaluru'),
(152, 'Avalahalli', 'West Zone', 'Bengaluru'),
(145, 'Vijayanagar', 'West Zone', 'Bengaluru'),
(147, 'Hampi Nagar', 'West Zone', 'Bengaluru'),
(146, 'Hosahalli', 'West Zone', 'Bengaluru'),
(160, 'Dharmaraya Swamy Temple', 'South Zone', 'Bengaluru'),
(161, 'Silver Jublee Park', 'South Zone', 'Bengaluru'),
(162, 'Sunkenahalli', 'South Zone', 'Bengaluru'),
(163, 'Vishveshwara Puram', 'South Zone', 'Bengaluru'),
(164, 'Hombegowda Nagar', 'South Zone', 'Bengaluru'),
(165, 'B Venkata Reddy Nagar', 'South Zone', 'Bengaluru'),
(196, 'Gavi Gangadhareshwara', 'South Zone', 'Bengaluru'),
(198, 'Dodda Ganapati', 'South Zone', 'Bengaluru'),
(199, 'Vidyapeeta ward', 'South Zone', 'Bengaluru'),
(200, 'Swamy Vivekananda', 'South Zone', 'Bengaluru'),
(201, 'Katriguppe', 'South Zone', 'Bengaluru'),
(197, 'Srinagar', 'South Zone', 'Bengaluru'),
(195, 'Hosakerehalli', 'South Zone', 'Bengaluru'),
(194, 'Chikkalsandra', 'South Zone', 'Bengaluru'),
(190, 'Devagiri Temple Ward', 'South Zone', 'Bengaluru'),
(188, 'Yediyur', 'South Zone', 'Bengaluru'),
(189, 'Ganesh Mandir ward', 'South Zone', 'Bengaluru'),
(191, 'Banashankari Temple ward', 'South Zone', 'Bengaluru'),
(192, 'Kumaraswamy Layout', 'South Zone', 'Bengaluru'),
(193, 'Padmanabha Nagar', 'South Zone', 'Bengaluru'),
(177, 'Lakkasandra', 'South Zone', 'Bengaluru'),
(175, 'Jakkasandra', 'South Zone', 'Bengaluru'),
(176, 'Adugodi', 'South Zone', 'Bengaluru'),
(174, 'Koramangala', 'South Zone', 'Bengaluru'),
(173, 'Ejipura', 'South Zone', 'Bengaluru'),
(178, 'Suddagunte Palya', 'South Zone', 'Bengaluru'),
(181, 'BTM Layout', 'South Zone', 'Bengaluru'),
(180, 'Someswara Temple Ward', 'South Zone', 'Bengaluru'),
(179, 'Madivala', 'South Zone', 'Bengaluru'),
(187, 'Sarakki', 'South Zone', 'Bengaluru'),
(184, 'Jayanagar East', 'South Zone', 'Bengaluru'),
(185, 'J P Nagar', 'South Zone', 'Bengaluru'),
(186, 'Shakambari Nagar', 'South Zone', 'Bengaluru'),
(183, 'Gurappanapalya', 'South Zone', 'Bengaluru'),
(182, 'Byrasandra', 'South Zone', 'Bengaluru'),
(224, 'Hosa Road', 'Bommanahalli', 'Bengaluru'),
(220, 'Gharebhavipalya', 'Bommanahalli', 'Bengaluru'),
(222, 'Ibluru', 'Bommanahalli', 'Bengaluru'),
(213, 'Jaraganahalli', 'Bommanahalli', 'Bengaluru'),
(214, 'Puttenahalli', 'Bommanahalli', 'Bengaluru'),
(215, 'Bilekhalli', 'Bommanahalli', 'Bengaluru'),
(216, 'Hulimavu', 'Bommanahalli', 'Bengaluru'),
(217, 'Kodichikkanahalli', 'Bommanahalli', 'Bengaluru'),
(219, 'Hongasandra', 'Bommanahalli', 'Bengaluru'),
(218, 'Bommanahalli', 'Bommanahalli', 'Bengaluru'),
(221, 'HSR Layout', 'Bommanahalli', 'Bengaluru'),
(223, 'Mangammanapalya', 'Bommanahalli', 'Bengaluru'),
(3, 'Atturu', 'Yelahanka', 'Bengaluru'),
(2, 'Chowdeswari Ward', 'Yelahanka', 'Bengaluru'),
(4, 'Yelahanka Satellite Town', 'Yelahanka', 'Bengaluru'),
(1, 'Kempegowda Ward', 'Yelahanka', 'Bengaluru')
ON DUPLICATE KEY UPDATE `ward_name` = VALUES(`ward_name`), `zone_name` = VALUES(`zone_name`), `city` = VALUES(`city`);
